name = input("Enter a your name: ")
nickname = input("Enter your nickname: ")
travel = input("Enter a your travelling place: ")
food = input("Enter your favourite food: ")
print("Welcome in Mad Libs Game !! "  +name )
print("Friends call you "  + nickname)
print("You want to travel "  + travel)
print("Your favourite food is "  + food)
print("Thanks for your good time!! see you again!!")
