name = input("Enter a your name: ")
nickname = input("Enter your nickname: ")
travel = input("Enter a your travelling place: ")
food = input("Enter your favourite food: ")
#subject = input("Enter your favourite subject: ")
#color = input("Enter a color: ")
#plural_noun = input("Enter a plural noun:  ")
#celebrity = input("Enter a celebrity: ")
print("Welcome in Mad Libs Game !! "  +name )
print("Friends call you "  + nickname)
print("You like to travel "  + travel)
print("Your favourite food is "  + food)
print("Thanks for your good time!! see you again!!")
#print("Your favourite subject is  "  + subject)

#print("Roses are "  + color)
#print(plural_noun + "are blue")
#print("I love " + celebrity)
